var  gleichungen={
            'C6H5NH3+': ['H₂O',     'C₆H₅NH₃⁺',     'H₃O⁺',         'C₆H₅NH₂',  
                         'wasser',  'aniliniumion', 'oxoniumion',   'anilin',
                         'Wasser',  'Aniliniumion', 'Oxoniumion',   'Anilin',
                         'white',   'white',        'orangered',    'white'],
            'NH4+':     ['H₂O',     'NH4⁺',         'H₃O⁺',         'NH₃', 
                         'wasser',  'ammoniumion',  'oxoniumion',   'ammoniak',
                         'Wasser',  'Ammoniumion',  'Oxoniumion',   'Ammoniak',
                         'white',   'white',        'darkorange',   'white'],
            'CH3COOH':  ['H₂O',     'CH₃COOH',      'H₃O⁺',         'CH₃COO⁻',  
                         'wasser',  'ethansaeure',  'oxoniumion',   'ethanoation',
                         'Wasser',  'Ethansäure',   'Oxoniumion',   'Ethanoation',
                         'white',   'white',        'darkorange',   'white'],
            'C6H5OH':   ['H₂O',     'C₆H₅OH',       'H₃O⁺',         'C₆H₅O⁻', 
                         'wasser',  'phenol',       'oxoniumion',   'phenolation',
                         'Wasser',  'Phenol',       'Oxoniumion',   'Phenolation',
                         'white',   'white',        'orange',       'white'],
            'CH3CH2OH': ['H₂O',     'CH₃CH₂OH',     'H₃O⁺',         'CH₃CH₂O⁻', 
                         'wasser',  'ethanol',      'oxoniumion',   'ethanolation',
                         'Wasser',  'Ethanol',      'Oxoniumion',   'Ethanolation',
                         'yellow',  'white',        'white',        'white'],
            'C6H5NH2':  ['C₆H₅NH₂', 'H₂O',          'C₆H₅NH₃⁺',     'OH⁻', 
                         'anilin',  'wasser',       'aniliniumion', 'hydroxidion',
                         'Anilin',  'Wasser',       'Aniliniumion', 'Hydroxidion',
                         'white',   'white',        'white',        'yellowgreen'],
            'NH3':      ['NH₃',     'H₂O',          'NH₄⁺',         'OH⁻', 
                         'ammoniak','wasser',       'ammoniumion',  'hydroxidion',
                         'Ammoniak','Wasser',       'Ammoniumion',  'Hydroxidion',
                         'white',   'white',        'white',        'forestgreen'],
            'CH3COO-':  ['CH₃COO⁻', 'H₂O',          'CH₃COOH',      'OH⁻', 
                         'ethanoation','wasser',     'ethansaeure',  'hydroxidion',
                         'Ethanoation','Wasser',     'Ethansäure',   'Hydroxidion',
                         'white',      'white',      'white',        'forestgreen'],
            'C6H5O-':   ['C₆H₅O⁻',  'H₂O',          'C₆H₅OH',       'OH⁻', 
                         'phenolation','wasser',    'phenol',       'hydroxidion',
                         'Phenolation','Wasser',    'Phenol',       'Hydroxidion',
                         'white',      'white',     'white',        'darkcyan'],
            'CH3CH2O-': ['CH₃CH₂O⁻','H₂O',          'CH₃CH₂OH',     'OH⁻',  
                         'ethanolation','wasser',   'ethanol',      'hydroxidion',
                         'Ethanolation','Wasser',   'Ethanol',      'Hydroxidion',
                         'white',       'white',    'white',        'blue',]
            };
