var disacchararide={
            'r1z1':['Maltose [Malzzucker]', 
                    'Ja',
                    'Abbauprodukt der Stärke, kommt z.B. in Gerstenkeimen und in Kartoffelkeimen vor. Maltose bildet sich u. a. beim Bierbrauen  durch Einwirkung von Amylasen auf Stärke.',
                    'malt'],
            'r1z3':['Trehalose', 
                    'Nein',
                    'Reserverstoff in Pflanzen, kann durch das Enzym Trehalase zu D-Glucose abgebaut werden. Wirkt als natürliches Frostschutzmittel in Bärtierchen.',
                    'treh'],
            'r1z4':['Isomaltose™', 
                    'Ja',
                    'Bildet die Verzweigungsstellen in Stärke.',
                    'isom'],
            'r1z5':['Isomaltulose [Palatinose]', 
                    'Nein',
                    'Erhöht den Blutzuckerspiegel langsamer als Saccharose und kann von Kariesbakterien nicht zur Säureproduktion verwendet werden.',
                    'isum'],
            'r2z2':['Cellobiose', 
                    'Ja',
                    'Grundbaustein der Cellulose, wird von Pflanzenfressern durch enzymatische Spaltung mit Hilfe von Einzellern aus Cellulose gewonnen.',
                    'cell'],
            'r3z3':['Saccharose [Haushaltszucker, Kristallzucker]', 
                    'Nein',
                    'Enthalten in Zuckerrübe, Zuckerrohr und Zuckerahorn, wird häufig als Süßungsmittel verwendet.',
                    'sacc'],
            'r4z2':['Lactose [Milchzucker]', 
                    'Ja',
                    'Enthalten in Milchprodukten. Die Spaltung während der Verdauung benötigt das Enzym Lactase.',
                    'lact'
                    ]
        }
