var hexosen={
    'aldose':{
                'rererere':'D-Allose',
                'lirerere':'D-Altrose',
                'relirere':'D-Glucose',
                'lilirere':'D-Mannose',
                'rerelire':'D-Gulose',
                'lirelire':'D-Idose',
                'relilire':'D-Galactose',
                'lililire':'D-Talose',
                'lililili':'L-Allose',
                'relilili':'L-Altrose',
                'lirelili':'L-Glucose',
                'rerelili':'L-Mannose',
                'lilireli':'L-Gulose',
                'relireli':'L-Idose',
                'lirereli':'L-Galactose',
                'rerereli':'L-Talose'},
    'ketose':{
                'rerere':'D-Psicose',
                'lirere':'D-Fructose',
                'relire':'D-Sorbose',
                'lilire':'D-Tagatose',
                'lilili':'L-Psicose',
                'relili':'L-Fructose',
                'lireli':'L-Sorbose',
                'rereli':'L-Tagatose'}
}
