var schritte_texte={
        0:'<u>Schritt 1</u>:<br />Die Stoff-Flüsse bewegen sich mit leichten jahreszeitlichen Schwankungen um einen relativ konstanten Mittelwert.',
        1:'<u>Schritt 2</u>:<br />Durch die Verbrennung fossiler Brennstoffe wird das dynamische Gleichgewicht gestört und die CO₂-Konzentration in der Atmosphäre wird erhöht. <br />Der Eintrag von CO₂ in die Atmosphäre über Vulkanausbrüche wird vernachlässigt, da hier nur der kurzfristige Kohlenstoffkreislauf (nur mit einer Dauer von bis zu maximal mehren Tausend Jahren) berücksichtigt wird.',
        2:'<u>Schritt 3</u>:<br />Kurzfristig kann ein Teil des überschüssigen CO₂ aus der Atmosphäre in Form von (v.a. pflanzlicher) Biomasse gebunden werden. <br />Dies ist ein Selbstheilungs- bzw. Selbstregulationsschritt durch eine negative Rückkopplung im Kreislauf.',
        3:'<u>Schritt 4</u>:<br />Kurzfristig kann ein weiterer Teil des überschüssigen CO₂ aus der Atmosphäre in den Ozeanen gelöst werden.<br />Dies ist ebenfalls ein Selbstheilungs- bzw. Selbstregulationsschritt durch eine negative Rückkopplung im Kreislauf.',
        4:'<u>Schritt 5</u>:<br />Können diese beiden Speicher aber nichts mehr aufnehmen, und wird die Verbrennung fossiler Brennstoffe unvermindert fortgesetzt, so steigt die CO₂-Konzentration in der Atmosphäre stark an.',
        5:'<u>Schritt 6</u>:<br />Durch den Treibhauseffekt erfolgt eine globale Erwärmung.',
        6:'<u>Schritt 7</u>:<br />Durch die höhere Temperatur nimmt die Destruententätigkeit anteilig stärker zu als die Primärproduktion von Biomasse durch die Produzenten (Pflanzen).<br />Dadurch wird netto noch mehr CO₂ aus der Biomasse in die Atmosphäre freigesetzt. <br />Dies ist ein, das Gleichgewicht zunehmend zerstörender, positiver Rückkopplungsschritt, der einen Teufelskreis in Gang setzt und immer weiter verstärkt.',
        7:'<u>Schritt 8</u>:<br />Durch die höhere Temperatur auch der Ozeane wird die Löslichkeit von CO₂ in den Ozeanen verringert, es wird vermehrt an die Atmosphäre abgegeben. <br />Die Temperatur steigt weiter an. <br />Dies ist ein weiterer, das Gleichgewicht zunehmend zerstörender, positiver Rückkopplungsschritt, der einen Teufelskreis in Gang setzt und immer weiter verstärkt.',
        8:'<u>Schritt 9</u>:<br />Durch den niedrigeren pH-Wert werden mehr Carbonatgesteine gelöst bzw. die Gesteinsbildung durch Meereslebewesen mit Kalkschale wird gestört. Es wird CO₂ aus dem Gestein freigesetzt und aus den Ozeanen in die Atmosphäre abgegeben. <br />Die Temperatur steigt noch weiter an. <br />Dies ist ein noch ein dritter, das Gleichgewicht zunehmend zerstörender, positiver Rückkopplungsschritt, der einen Teufelskreis in Gang setzt und immer weiter verstärkt.',
        9:'<u>Schritt 10</u>:<br />Der gestiegene CO₂-Gehalt in der Atmosphäre führt zu einer weiteren globalen Erwärmung der Atmosphäre. <br />Durch die sich selbst und gegenseitig immer weiter verstärkenden positiven Rückkopplungsschritte, wird ein Teufelskreis wahrscheinlich, der zu einer sehr starken Erwärmung führt.'
}
