sammlung_zusatzinformationen={
// 1. Periode
'HH':'elementarer Wasserstoff, H₂, Siedepunkt: -252 °C, farbloses Gas',
'HLi':'',
'HBe':'',
'HB':'',
'HC':'Methan, CH₄, Siedepunkt: -162 °C, farbloses Gas',
'HN':'Ammoniak, NH₃, Siedepunkt: -33 °C, farbloses Gas',
'HO':'Wasser, H₂O, Siedepunkt: 0 °C, farblose Flüssigkeit',
'HF':'Fluorwasserstoff, HF, Siedepunkt: 19,5 °C, farbloses Gas',
'HNa':'',
'HMg':'',
'HAl':'',
'HSi':'',
'HP':'Phosphin, PH₃, Siedepunkt: -87,8 °C, farbloses Gas',
'HS':'Schwefelwasserstoff, H₂S, Siedepunkt: -60,2 °C, farbloses Gas',
'HCl':'Chlorwasserstoff, HCl, Siedepunkt: -85,0 °C, farbloses Gas',
// 2. Periode
// Li
'LiH':'',
'LiLi':'elementares Lithium, Schmelzpunkt: 180,5 °C, silbrig weißer Feststoff',
'LiBe':'',
'LiB':'',
'LiC':'',
'LiN':'Lithiumnitrid, LiN₃, Schmelzpunkt: 845 °C, rot-braunes Pulver',
'LiO':'Lithiumoxid, Li₂O, Schmelzpunkt: 1427 °C, weißer Feststoff',
'LiF':'Lithiumfluorid, LiF,  Schmelzpunkt: 845 °C, farbloser bis weißer Feststoff',
'LiNa':'',
'LiMg':'',
'LiAl':'',
'LiSi':'',
'LiP':'',
'LiS':'Lithiumsulfid, Li₂S, Schmelzpunkt: 1372 °C, farbloser Feststoff',
'LiCl':'Lithiumchlorid, LiCl, Schmelzpunkt: 615 °C, weißer Feststoff',
// Be
'BeH':'',
'BeLi':'',
'BeBe':'elementares Beryllium, Schmelzpunkt: 1287 °C, silbrig weißer Feststoff',
'BeB':'',
'BeC':'',
'BeN':'',
'BeO':'',
'BeF':'Berylliumfluorid, BeF₂, Schmelzpunkt: 555 °C, farbloser Feststoff',
'BeNa':'',
'BeMg':'',
'BeAl':'',
'BeSi':'',
'BeP':'',
'BeS':'',
'BeCl':'',
// B
'BH':'',
'BLi':'',
'BBe':'',
'BB':'elementares Bor',
'BC':'',
'BN':'',
'BO':'',
'BF':'',
'BNa':'',
'BMg':'',
'BAl':'',
'BSi':'',
'BP':'',
'BS':'',
'BCl':'',
// C
'CH':'Methan, CH₄, Siedepunkt: -162 °C, farbloses Gas',
'CLi':'',
'CBe':'',
'CB':'',
'CC':'elementarer Kohlenstoff',
'CN':'',
'CO':'Kohlenstoffdioxid, CO₂, Sublimationspunkt: -78,5 °C, farbloses Gas',
'CF':'Tetrafluormethan, CF₄, Siedepunkt: -128 °C, farbloses Gas',
'CNa':'',
'CMg':'',
'CAl':'',
'CSi':'',
'CP':'',
'CS':'Kohlenstoffdisulfid, CS₂, Siedepunkt: 46,3 °C, farblose Flüssigkeit',
'CCl':'Tetrachlormethan, CCl₄, Siedepunkt: 76 °C, farblose Flüssigkeit',
// N
'NH':'Ammoniak, NH₃, Siedepunkt: -33 °C, farbloses Gas',
'NLi':'Lithiumnitrid, LiN₃, Schmelzpunkt: 845 °C, rot-braunes Pulver',
'NBe':'',
'NB':'',
'NC':'',
'NN':'elementarer Stickstoff, Siedepunkt: -196 °C, farbloses Gas',
'NO':'',
'NF':'Stickstofftrifluorid, NF₃, Siedepunkt: -128,8 °C, farbloses Gas',
'NNa':'',
'NMg':'',
'NAl':'',
'NSi':'',
'NP':'',
'NS':'',
'NCl':'Stickstofftrichlorid, NCl₃, Siedepunkt: 71 °C, gelbe (explosive) Flüssigkeit',
// O
'OH':'Wasser, H₂O, Siedepunkt: 0 °C, farblose Flüssigkeit',
'OLi':'Lithiumoxid, Li₂O, Schmelzpunkt: 1427 °C, weißer Feststoff',
'OBe':'',
'OB':'',
'OC':'Kohlenstoffdioxid, CO₂, Sublimationspunkt: -78,5 °C, farbloses Gas',
'ON':'Stickstoffdioxid, NO₂, Siedepunkt: 21,2 °C, rotbraunes Gas',
'OO':'elementarer Sauerstoff, Siedepunkt: -183 °C, farbloses Gas',
'OF':'',
'ONa':'Natriumoxid, Na₂O, Sublimationspunkt: 1275 °C, weißer Feststoff',
'OMg':'Magnesiumoxid, MgO, Schmelzpunkt: 2852 °C, weißer Feststoff',
'OAl':'Aluminiumoxid, Al₂O₃, Schmelzpunkt: 2050 °C, weißer Feststoff',
'OSi':'Siliciumdioxid, SiO₂ (Atomgitter!), Schmelzpunkt: 1713 °C, farbloser Feststoff',
'OP':'Tetraphosphordecaoxid, P₄O₁₀, Schmelzpunkt: 350 °C, farbloser Feststoff',
'OS':'Schwefeldioxid, SO₂, Siedepunkt: -10 °C, farbloses Gas',
'OCl':'',
// F
'FH':'Fluorwasserstoff, HF, Siedepunkt: 19,5 °C, farbloses Gas',
'FLi':'Lithiumfluorid, LiF,  Schmelzpunkt: 845 °C, farbloser bis weißer Feststoff',
'FBe':'Berylliumfluorid, BeF₂, Schmelzpunkt: 555 °C, farbloser Feststoff',
'FB':'',
'FC':'Tetrafluormethan, CF₄, Siedepunkt: -128 °C, farbloses Gas',
'FN':'Stickstofftrifluorid, NF₃, Siedepunkt: -128,8 °C, farbloses Gas',
'FO':'',
'FF':'elementares Fluor, Siedepunkt: -188 °C, gelbliches Gas',
'FNa':'Natriumfluorid, NaF, Schmelzpunkt: 993 °C, weißer Feststoff',
'FMg':'Magnesiumfluorid, MgF₂, Schmelzpunkt: 1256 °C, farbloser Feststoff',
'FAl':'Aluminiumfluorid, AlF₃ Sublimationspunkt: 1260 °C, farbloser Feststoff',
'FSi':'Siliciumtetrafluorid, SiF₄, Sublimationspunkt: -95,2 °C, farbloses Gas',
'FP':'Phosphor(III)-fluorid, PF₃, Siedepunkt: -95,2 °C, farbloses Gas',
'FS':'Schwefeldifluorid, SF₂, instabil, farbloses Gas',
'FCl':'Chlorfluorid, ClF, Siedepunkt: -101,1 °C, farbloses Gas',
// 3. Periode
// Na
'NaH':'',
'NaLi':'',
'NaBe':'',
'NaB':'',
'NaC':'',
'NaN':'',
'NaO':'Natriumoxid, Na₂O, Sublimationspunkt: 1275 °C, weißer Feststoff',
'NaF':'Natriumfluorid, NaF, Schmelzpunkt: 993 °C, weißer Feststoff',
'NaNa':'elementares Natrium, Schmelzpunkt: 97,7 °C, silbrig weißer Feststoff',
'NaMg':'',
'NaAl':'',
'NaSi':'',
'NaP':'',
'NaS':'Natriumsulfid, Na₂S, Schmelzpunkt: 1180 °C, farbloser Feststoff',
'NaCl':'Natriumchlorid, NaCl, Schmelzpunkt: 1465 °C, farbloser Feststoff',
// Mg
'MgH':'',
'MgLi':'',
'MgBe':'',
'MgB':'',
'MgC':'',
'MgN':'',
'MgO':'Magnesiumoxid, MgO, Schmelzpunkt: 2852 °C, weißer Feststoff',
'MgF':'Magnesiumfluorid, MgF₂, Schmelzpunkt: 1256 °C, farbloser Feststoff',
'MgNa':'',
'MgMg':'elementares Magnesium, Schmelzpunkt: 650 °C, silbrig weißer Feststoff',
'MgAl':'',
'MgSi':'',
'MgP':'',
'MgS':'Magnesiumsulfid, MgS, Schmelzpunkt: > 2000 °C, weißes bis rötliches Pulver',
'MgCl':'Magnesiumchlorid, MgCl₂, Schmelzpunkt: 708 °C, farbloses Pulver',
// Al
'AlH':'',
'AlLi':'',
'AlBe':'',
'AlB':'',
'AlC':'',
'AlN':'',
'AlO':'Aluminiumoxid, Al₂O₃, Schmelzpunkt: 2050 °C, weißer Feststoff',
'AlF':'Aluminiumfluorid, AlF₃ Sublimationspunkt: 1260 °C, farbloser Feststoff',
'AlNa':'',
'AlMg':'',
'AlAl':'elementares Aluminium, Schmelzpunkt: 660,3 °C, silbriger Feststoff',
'AlSi':'',
'AlP':'',
'AlS':'Aluminiumsulfid, Al₂S₃, Schmelzpunkt: 1100 °C, gelblicher Feststoff',
'AlCl':'Aluminiumchlorid, AlCl₃, Sublimationspunkt: 180 °C, weißer Feststoff',
// Si
'SiH':'',
'SiLi':'',
'SiBe':'',
'SiB':'',
'SiC':'',
'SiN':'',
'SiO':'Siliciumdioxid, SiO₂ (Atomgitter!), Schmelzpunkt: 1713 °C, farbloser Feststoff',
'SiF':'Siliciumtetrafluorid, SiF₄, Sublimationspunkt: -95,2 °C, farbloses Gas',
'SiNa':'',
'SiMg':'',
'SiAl':'',
'SiSi':'elementares Silizium',
'SiP':'',
'SiS':'',
'SiCl':'',
// P
'PH':'Phosphin, PH₃, Siedepunkt: -87,8 °C, farbloses Gas',
'PLi':'',
'PBe':'',
'PB':'',
'PC':'',
'PN':'',
'PO':'Tetraphosphordecaoxid, P₄O₁₀, Schmelzpunkt: 350 °C, farbloser Feststoff',
'PF':'Phosphor(III)-fluorid, PF₃, Siedepunkt: -95,2 °C, farbloses Gas',
'PNa':'',
'PMg':'',
'PAl':'',
'PSi':'',
'PP':'elementarer Phosphor',
'PS':'',
'PCl':'',
// S
'SH':'Schwefelwasserstoff, H₂S, Siedepunkt: -60,2 °C, farbloses Gas',
'SLi':'Lithiumsulfid, Li₂S, Schmelzpunkt: 1372 °C, farbloser Feststoff',
'SBe':'',
'SB':'',
'SC':'Kohlenstoffdisulfid, CS₂, Siedepunkt: 46,3 °C, farblose Flüssigkeit',
'SN':'',
'SO':'Schwefeldioxid, SO₂, Siedepunkt: -10 °C, farbloses Gas',
'SF':'Schwefeldifluorid, SF₂, instabil, farbloses Gas',
'SNa':'Natriumsulfid, Na₂S, Schmelzpunkt: 1180 °C, farbloser Feststoff',
'SMg':'Magnesiumsulfid, MgS, Schmelzpunkt: > 2000 °C, weißes bis rötliches Pulver',
'SAl':'Aluminiumsulfid, Al₂S₃, Schmelzpunkt: 1100 °C, gelblicher Feststoff',
'SSi':'',
'SP':'',
'SS':'elementarer Schwefel, S₈, Schmelzpunkt: 115,2 °C, gelber Feststoff',
'SCl':'',
// Cl
'ClH':'Chlorwasserstoff, HCl, Siedepunkt: -85,0 °C, farbloses Gas',
'ClLi':'Lithiumchlorid, LiCl, Schmelzpunkt: 615 °C, weißer Feststoff',
'ClBe':'',
'ClB':'',
'ClC':'Tetrachlormethan, CCl₄, Siedepunkt: 76 °C, farblose Flüssigkeit',
'ClN':'Stickstofftrichlorid, NCl₃, Siedepunkt: 71 °C, gelbe (explosive) Flüssigkeit',
'ClO':'',
'ClF':'Chlorfluorid, ClF, Siedepunkt: -101,1 °C, farbloses Gas',
'ClNa':'Natriumchlorid, NaCl, Schmelzpunkt: 1465 °C, farbloser Feststoff',
'ClMg':'Magnesiumchlorid, MgCl₂, Schmelzpunkt: 708 °C, farbloses Pulver',
'ClAl':'Aluminiumchlorid, AlCl₃, Sublimationspunkt: 180 °C, weißer Feststoff',
'ClSi':'',
'ClP':'',
'ClS':'',
'ClCl':'elementares Chlor, Siedepunkt: -34,6 °C, grünes Gas'
};
